source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-gist", "~> 1.5"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-redirect-from", "~> 0.16"
gem "jemoji", "~> 0.13"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.8"